name: Android-OLLVM-NDK

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ssageparuders/android_llvm_14.06:18.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build SsagePass (fix hard-coded compiler)
        run: |
          docker run --rm \
            -v "$PWD":/workspace \
            -w /workspace/Obfuscation \
            ssageparuders/android_llvm_14.06:18.04 \
            bash -c "
              set -e
              rm -rf build && mkdir build && cd build
              cmake .. \
                -DCMAKE_BUILD_TYPE=Release \
                -DLLVM_DIR=/opt/llvm-14.0.6/lib/cmake/llvm \
                -DCMAKE_C_COMPILER=/opt/llvm-14.0.6/bin/clang \
                -DCMAKE_CXX_COMPILER=/opt/llvm-14.0.6/bin/clang++
              make -j\$(nproc)
            "
"

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: aide-ollvm-ndk.tar.gz
          name: Android OLLVM NDK ${{ github.ref_name }}
          body: |
            预编译的 SsagePass LLVM Pass 动态库（Android NDK r25）
            用法：
            1. 解压 `aide-ollvm-ndk.tar.gz` 到任意目录
            2. 在 AIDE 的 `Application.mk` 或 `CMakeLists.txt` 里添加：
               ```
               LOCAL_CPPFLAGS += -fpass-plugin=/path/to/libSsageObfuscator.so
               ```
            3. 在需要混淆的函数上添加：
               ```cpp
               __attribute((__annotate__(("fla split strenc"))))
               ```
